import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

/**
 * Merge Tailwind classes with clsx
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * Format date for display
 */
export function formatDate(date: Date | string, locale: string = 'en') {
  const d = new Date(date);
  return new Intl.DateTimeFormat(locale === 'am' ? 'am-ET' : 'en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  }).format(d);
}

/**
 * Format relative time (e.g., "2 hours ago")
 */
export function formatRelativeTime(date: Date | string, locale: string = 'en') {
  const d = new Date(date);
  const now = new Date();
  const diffMs = now.getTime() - d.getTime();
  const diffSecs = Math.floor(diffMs / 1000);
  const diffMins = Math.floor(diffSecs / 60);
  const diffHours = Math.floor(diffMins / 60);
  const diffDays = Math.floor(diffHours / 24);

  const rtf = new Intl.RelativeTimeFormat(locale === 'am' ? 'am' : 'en', {
    numeric: 'auto',
  });

  if (diffDays > 0) return rtf.format(-diffDays, 'day');
  if (diffHours > 0) return rtf.format(-diffHours, 'hour');
  if (diffMins > 0) return rtf.format(-diffMins, 'minute');
  return rtf.format(-diffSecs, 'second');
}

/**
 * Format number with locale
 */
export function formatNumber(num: number, locale: string = 'en') {
  return new Intl.NumberFormat(locale === 'am' ? 'am-ET' : 'en-US').format(num);
}

/**
 * Truncate text with ellipsis
 */
export function truncate(str: string, length: number) {
  if (str.length <= length) return str;
  return str.slice(0, length) + '...';
}

/**
 * Generate Mapbox static map URL
 */
export function getStaticMapUrl(
  lng: number,
  lat: number,
  width: number = 300,
  height: number = 200,
  zoom: number = 14
) {
  const token = process.env.NEXT_PUBLIC_MAPBOX_TOKEN;
  return `https://api.mapbox.com/styles/v1/mapbox/dark-v11/static/pin-s+14b8a6(${lng},${lat})/${lng},${lat},${zoom},0/${width}x${height}@2x?access_token=${token}`;
}

/**
 * Category configuration
 */
export const categories = {
  roads: {
    label: { en: 'Roads', am: 'መንገዶች' },
    color: '#F59E0B', // Amber
    icon: 'road',
  },
  water: {
    label: { en: 'Water', am: 'ውሃ' },
    color: '#3B82F6', // Blue
    icon: 'droplets',
  },
  sanitation: {
    label: { en: 'Sanitation', am: 'ንጽህና' },
    color: '#10B981', // Green
    icon: 'trash-2',
  },
  lighting: {
    label: { en: 'Lighting', am: 'መብራት' },
    color: '#eab308',
    icon: 'lightbulb',
  },
  safety: {
    label: { en: 'Safety', am: 'ደህንነት' },
    color: '#EF4444', // Red
    icon: 'shield-alert',
  },
  parks: {
    label: { en: 'Parks', am: 'ፓርኮች' },
    color: '#059669',
    icon: 'trees',
  },
} as const;

export type Category = keyof typeof categories;

/**
 * Status configuration
 */
export const statuses = {
  open: {
    label: { en: 'Open', am: 'ክፍት' },
    color: '#f59e0b',
  },
  in_progress: {
    label: { en: 'In Progress', am: 'በሂደት ላይ' },
    color: '#3b82f6',
  },
  resolved: {
    label: { en: 'Resolved', am: 'ተፈትቷል' },
    color: '#10b981',
  },
  closed: {
    label: { en: 'Closed', am: 'ተዘግቷል' },
    color: '#6b7280',
  },
} as const;

export type Status = keyof typeof statuses;

/**
 * Translate database notification messages to the current locale
 */
export function translateNotification(message: string, locale: string, t: any) {
  if (!message) return "";
  
  // Regex patterns for English messages generated by triggers
  const patterns = [
    {
      regex: /^Your issue "(.*)" is now (.*)\.$/,
      key: 'status_change_owner',
      map: (match: any) => ({ issue: match[1], status: match[2] })
    },
    {
      regex: /^The issue "(.*)" you are following is now (.*)\.$/,
      key: 'status_change_follower',
      map: (match: any) => ({ issue: match[1], status: match[2] })
    },
    {
      regex: /^(.*) upvoted your issue: "(.*)"$/,
      key: 'upvote',
      map: (match: any) => ({ actor: match[1], issue: match[2] })
    },
    {
      regex: /^Someone upvoted your issue: "(.*)"$/,
      key: 'generic_upvote',
      map: (match: any) => ({ issue: match[1] })
    },
    {
       regex: /^(.*) followed your issue: "(.*)"$/,
       key: 'follow',
       map: (match: any) => ({ actor: match[1], issue: match[2] })
    },
    {
       regex: /^(.*) commented on your issue: "(.*)"$/,
       key: 'comment',
       map: (match: any) => ({ actor: match[1], issue: match[2] })
    }
  ];

  for (const p of patterns) {
    const match = message.match(p.regex);
    if (match) {
      const params = p.map(match) as any;
      // Localize status if present
      if (params.status) {
        const statusKey = params.status.toLowerCase().replace(' ', '_');
        params.status = statuses[statusKey as Status]?.label[locale as 'en' | 'am'] || params.status;
      }
      return t(`templates.${p.key}`, params);
    }
  }

  return message; // Fallback to original message
}
